# Generated by Django 4.0.5 on 2022-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('RAM', models.CharField(blank=True, max_length=20, null=True)),
                ('gpu', models.CharField(blank=True, max_length=20, null=True)),
                ('cpu', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
